# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d83381145f44f8df86e938f6fffa330c989957736eb824f5ac858893304b264479a3438c7905ad09293a57bbf23a1e46fe40a9f6090ed537ad938cf573094a0

test:
  secret_key_base: 91a526b79c5dd5a0cd6602ff43286a724996fb02dc9cb93c997414906ae48d08eb0356d558f04e287deffd08bc71dbcf348227ed9dd9a2ece6b430250a0aa06f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
